# All dependencies are installed in this image
image: jengelen/finitefield

build:
  stage: build

  script:
    - mkdir build && cd build
    - cmake ..
    - make
    - make test
    - make bench
    - ./benchmarks/bench
